-- msgtype.lua

MSG_TYPE_SOCKET_SENDCLIENTMSG = 11
MSG_TYPE_SOCKET_RECVCLIENTMSG = 12
MSG_TYPE_SOCKET_CONNECTIONBREAK = 13
MSG_TYPE_SOCKET_KICKOFFCONNECTION = 14
MSG_TYPE_SOCKET_REMOVECONNECTION = 15

MSG_TYPE_ECHO = 1000
MSG_TYPE_PLAYER_LOGIN = 1001

