-- msgtype.lua

local msgtypes = {
	SOCKET_SENDCLIENTMSG = 11, 
	SOCKET_RECVCLIENTMSG = 12,
	SOCKET_CONNECTIONBREAK = 13,
	SOCKET_KICKOFFCONNECTION = 14,
	SOCKET_REMOVECONNECTION = 15,
	
	PLAYER_ECHO = 1000,
	PLAYER_LOGIN = 1001,
}

return msgtypes

