#pragma once

#define MSG_TYPE_SOCKET_SENDCLIENTMSG		1001
#define MSG_TYPE_SOCKET_RECVCLIENTMSG		1002
#define MSG_TYPE_SOCKET_CONNECTIONBREAK		1003
#define MSG_TYPE_SOCKET_KICKOFFCONNECTION	1004
#define MSG_TYPE_SOCKET_REMOVECONNECTION	1005

